# Generated by Django 4.2.5 on 2023-10-08 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('rank', models.PositiveIntegerField(unique=True, verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'カテゴリー',
                'verbose_name_plural': 'カテゴリー',
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='本文')),
                ('handle_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='ハンドルネーム')),
                ('view_count', models.IntegerField(default=0, verbose_name='閲覧数')),
                ('reply_count', models.IntegerField(default=0, verbose_name='返信数')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='非表示フラグ')),
                ('closed', models.BooleanField(default=False, verbose_name='閉鎖')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forum.category', verbose_name='カテゴリー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'スレッド',
                'verbose_name_plural': 'スレッド',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle_name', models.CharField(blank=True, default='', max_length=10, verbose_name='ハンドルネーム')),
                ('content', models.TextField(verbose_name='本文')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='非表示フラグ')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.thread', verbose_name='スレッド')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '返信',
                'verbose_name_plural': '返信',
                'ordering': ['-create_date'],
            },
        ),
    ]
