# Generated by Django 4.2.5 on 2023-10-08 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.TextField(max_length=3000, verbose_name='内容')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日時')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_info', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_info', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'ordering': ['-release_date'],
            },
        ),
    ]
